### ISSUE TITLE
Improve base url path support in BaseUrlSession

### ISSUE THREAD

**Issue by dchevell** [requests/toolbelt#238] opened 2019-01-19 02:13 UTC
As noted in the docstring for `BaseUrlSession`, `urllib.parse.urljoin()` is very picky about trailing / leading slashes when joining a base url containing a path (e.g. https://example.com/jira) with a relative url path. Whilst expected behaviour for `urljoin()` itself, its use here leads to inconsistent behaviour for users of this library:

* If my base URL doesn't include a context path, my subsequent requests can use relative URL's with or without a leading slash. If my base URL does include a context path, it will be silently dropped if my requests begin with a leading slash
* My base URL doesn't need a trailing slash to be well formatted without a context path, but does need a trailing slash to be well formatted with a context path or else the context path will be silently 

To put it another way, when not using a context path, all of the following examples work as expected:

```python
s = BaseUrlSession(base_url='https://example.com')
s.get('test')
# GET /test

s = BaseUrlSession(base_url='https://example.com/')
s.get('test')
# GET /test

s = BaseUrlSession(base_url='https://example.com')
s.get('/test')
# GET /test

s = BaseUrlSession(base_url='https://example.com/')
s.get('/test')
# GET /test
```

When using a context path, only the second of the following examples works:

```python
s = BaseUrlSession(base_url='https://example.com/jira')
s.get('test')
# GET /test

s = BaseUrlSession(base_url='https://example.com/jira/')
s.get('test')
# GET /jira/test

s = BaseUrlSession(base_url='https://example.com/jira')
s.get('/test')
# GET /test

s = BaseUrlSession(base_url='https://example.com/jira/')
s.get('/test')
# GET /test
```

Given the purpose of `BaseUrlSession` there should be no case where dropping the context path is ever a desired behaviour. The urllib docs suggest that `urlsplit()` and `urlunsplit()` should be used if this behaviour isn't desired, so this would provide a more foolproof solution

**Comment by dchevell** [comment] 2019-01-19 03:40
An alternative here would be to coerce the URL parts to match what `urljoin()` is expecting by adding a trailing slash to the base url during initialisation, and stripping leading slashes from relative url's for any requests:

```python
def __init__(self, base_url=None):
    if base_url:
        self.base_url = base_url + '/'
    super(BaseUrlSession, self).__init__()
```
```python
def create_url(self, url):
    """Create the URL based off this partial path."""
    return urljoin(self.base_url, url.lstrip('/'))
```

Whilst naive, it works and is simpler than fully deconstructing and reconstructing the url with `urlsplit()` and `urlunsplit()`

**Comment by sigmavirus24** [comment] 2019-01-19 12:49
This was really the chief reason Requests never added this to the core. Most people will have vastly different expectations of how this should work when in fact it's actually a well specified algorithm by RFC 3986. Specifically this is called [Reference Resolution](http://tools.ietf.org/html/rfc3986#section-5).

Right now, I think this is the most straight forward implementation. Could it be better documented? Absolutely it probably could.

`create_url` was specifically pulled into its own method so that users could make their subclassed sessions behave *exactly* as they wish.

With that in mind, I'm going to close this because I believe it's the least controversial implementation and it's not dififcult for end users to change if its behaviour doesn't match their own intuition.

**Closed by sigmavirus24** 2019-01-19 12:49 UTC

**Comment by dchevell** [comment] 2019-01-20 09:49
I understand your reasoning, it's just a bit of a shame that this has to be subclassed in order to work reliably for such a common case. Thanks for following up all the same.

**Comment by sigmavirus24** [comment] 2019-01-21 13:52
I think the problem is that of perception and the fact that there is a complete lack of a evidence-based understanding of what is actually common. I think it's totally reasonable for you to feel as if your situation is common. I have a vastly different set of experiences and expectations, so my opinion is that it's not as common as you think it is. Based on the fact that we're just using urljoin from the stdlib and following the behaviour outlined in a thirteen (nearly fourteen) year old specification, I think the current behaviour is the least likely to be surprising.

I'd be happy to merge improved documentation around this.
